name: Backend Tests

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Adjust the Java version as needed

      - name: Build and Test Backend
        run: |
          cd backend  # Change to your Spring Boot backend directory
          ./gradlew clean build
        working-directory: backend  # Specify the path to your Spring Boot backend directory
